import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About TECH-O-NICKS",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return <main className="pt-[120px]">{children}</main>;
};

export default layout;
