import type { Metadata } from "next";
import { Roboto ,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"] ,weight:"400"});
const poppins = Poppins({ subsets: ["latin"] ,weight:"400"});

export const metadata: Metadata = {
  title: "TECH-O-NICKS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen custom-scrollbar`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
